

SELECT * FROM TABS;

-- 제품 테이블
-- 테이블명: PRODUCT
-- 속성: ID, NAME, PRICE, MNO(메뉴 ID)

-- 메뉴 테이블
-- 테이블명: MENU
--  속성: ID, NAME

CREATE TABLE PRODUCT(ID NUMBER(4),NAME VARCHAR2(20),PRICE NUMBER,MNO NUMBER(2)
                    ,CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(ID));
                    
SELECT * FROM TABS;

CREATE TABLE MENU(ID NUMBER(2),NAME VARCHAR2(20)
                    ,CONSTRAINT MENU_ID_PK PRIMARY KEY(ID));


ALTER TABLE PRODUCT ADD(CONSTRAINT PRODUCT_MNO_FK FOREIGN KEY(MNO) REFERENCES MENU(ID));


SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS;


INSERT INTO MENU VALUES(10,'커피');
COMMIT;
INSERT INTO MENU VALUES(20,'음료'||chr(38)||'차');
COMMIT;
INSERT INTO MENU VALUES(30,'디저트');
COMMIT;
INSERT INTO MENU VALUES(40,'베이글');
COMMIT;

SELECT * FROM PRODUCT;

ALTER TABLE PRODUCT MODIFY (NAME VARCHAR2(40));

INSERT INTO PRODUCT VALUES(1001,'아이스 아메리카노(R)', 4100,10);
INSERT INTO PRODUCT VALUES(1002,'아이스 아메리카노(L)', 4600,10);
INSERT INTO PRODUCT VALUES(1003,'아메리카노(R)', 4100,10);
INSERT INTO PRODUCT VALUES(1004,'아메리카노(L)', 4600,10);

INSERT INTO PRODUCT VALUES(1005,'에스프레소(R)', 3500,10);
INSERT INTO PRODUCT VALUES(1006,'에스프레소(L)', 4000,10);

INSERT INTO PRODUCT VALUES(1007,'카라멜마끼야또(R)', 5100,10);
INSERT INTO PRODUCT VALUES(1008,'카라멜마끼야또(L)', 5600,10);

INSERT INTO PRODUCT VALUES(1009,'아이스 카라멜마끼야또(R)', 5100,10);
INSERT INTO PRODUCT VALUES(1010,'아이스 카라멜마끼야또(L)', 5600,10);

INSERT INTO PRODUCT VALUES(1011,'바닐라 라떼(R)', 5000,10);
INSERT INTO PRODUCT VALUES(1012,'바닐라 라떼(L)', 5500,10);

INSERT INTO PRODUCT VALUES(1013,'아이스 바닐라 라떼(R)', 5000,10);
INSERT INTO PRODUCT VALUES(1014,'아이스 바닐라 라떼(L)', 5500,10);

INSERT INTO PRODUCT VALUES(1015,'카페라떼(R)', 4600,10);
INSERT INTO PRODUCT VALUES(1016,'카페라떼(L)', 4600,10);

INSERT INTO PRODUCT VALUES(1017,'아이스 카페라떼(R)', 4600,10);
INSERT INTO PRODUCT VALUES(1018,'아이스 카페라떼(L)', 4600,10);

INSERT INTO PRODUCT VALUES(1019,'카푸치노(R)', 4600,10);
INSERT INTO PRODUCT VALUES(1020,'카푸치노(L)', 5100,10);

COMMIT;
SELECT * FROM PRODUCT;
ROLLBACK;

DESC PRODUCT;

SELECT PRODUCT.ID,PRODUCT.NAME,PRICE,MENU.NAME AS MNAME FROM PRODUCT JOIN MENU ON PRODUCT.MNO = MENU.ID;


INSERT INTO PRODUCT VALUES(1021,'잉글리쉬블랙퍼스트(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1022,'잉글리쉬블랙퍼스트(L)', 5000,20);

INSERT INTO PRODUCT VALUES(1023,'아이스 잉글리쉬블랙퍼스트(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1024,'아이스 잉글리쉬블랙퍼스트(L)', 5000,20);

--
INSERT INTO PRODUCT VALUES(1025,'얼그레이(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1026,'얼그레이(L)', 5000,20);
INSERT INTO PRODUCT VALUES(1027,'아이스 얼그레이(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1028,'아이스 얼그레이(L)', 5000,20);


--
INSERT INTO PRODUCT VALUES(1029,'캐모마일(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1030,'캐모마일(L)', 5000,20);
INSERT INTO PRODUCT VALUES(1031,'아이스 캐모마일(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1032,'아이스 캐모마일(L)', 5000,20);

SELECT * FROM PRODUCT;
COMMIT;
--
INSERT INTO PRODUCT VALUES(1033,'유자차(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1034,'유자차(L)', 5000,20);
INSERT INTO PRODUCT VALUES(1035,'아이스 유자차(R)', 4000,20);
INSERT INTO PRODUCT VALUES(1036,'아이스 유자차(L)', 5000,20);

INSERT INTO PRODUCT VALUES(1037,'팥빙수', 8900,30);
INSERT INTO PRODUCT VALUES(1038,'커피빙수', 9800,30);
INSERT INTO PRODUCT VALUES(1039,'딸기빙수', 9800,30);

INSERT INTO PRODUCT VALUES(1040,'플레인', 1900,40);
INSERT INTO PRODUCT VALUES(1041,'블루베리', 1900,40);
INSERT INTO PRODUCT VALUES(1042,'어니언', 1900,40);
INSERT INTO PRODUCT VALUES(1043,'크렌베리', 1900,40);

INSERT INTO PRODUCT VALUES(1044,'크림치즈-플레인', 1900,40);
INSERT INTO PRODUCT VALUES(1045,'크림치즈-블루베리치즈케이크', 1900,40);
INSERT INTO PRODUCT VALUES(1046,'크림치즈-허브갈릭', 1900,40);
INSERT INTO PRODUCT VALUES(1047,'크림치즈-크렌베리아몬드', 1900,40);


-- 매장
CREATE TABLE STORE(ID NUMBER(4),NAME VARCHAR(20)
                            ,CONSTRAINT STORE_ID_PK PRIMARY KEY(ID));

DESC STORE;

INSERT INTO STORE VALUES(1001,'아이티윌 매장');
COMMIT;
SELECT * FROM STORE;

-- 구매
-- 클라이언트에서 프로시저로 호출 한다.
-- 아이디, 가격, 결재 날짜, 매장아이디, 물품 정보
CREATE TABLE PURCHASE(ID NUMBER,PRICE NUMBER,PAYMENTDAY DATE  DEFAULT SYSDATE,SNO NUMBER(4),
                        PLNO NUMBER);

-- 구매 리스트
-- 구매 아이디,
-- 구매 번호
-- 구매 내역
CREATE TABLE PURCHASELIST(ID NUMBER,PNO NUMBER,AMOUNT NUMBER(3));

-- 구매 번호에 해당하는 시컨스 생성

create sequence PURCHASE_SEQ;

-- 검색
SELECT * FROM PURCHASE;
SELECT * FROM PURCHASELIST;
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'PURCHASE_SEQ';
SELECT * FROM USER_SEQUENCES;
-- 삭제
DELETE FROM PURCHASE;
DELETE FROM PURCHASELIST;
DROP SEQUENCE PURCHASE_SEQ;
COMMIT;

DESC PURCHASE;
DESC PURCHASELIST;



SELECT PURCHASE_SEQ.NEXTVAL FROM DUAL;

INSERT INTO PURCHASELIST VALUES(1,1001,5);

DESC PURCHASE;
DESC STORE;

INSERT INTO PURCHASE(ID,PRICE,SNO,PLNO) VALUES(1,5000,1001,1);

COMMIT;



SELECT ID,PRICE,PAYMENTDAY FROM PURCHASE ORDER BY PAYMENTDAY;
DESC PURCHASELIST;
DESC PRODUCT;

SELECT P.NAME,PL.AMOUNT FROM PURCHASELIST PL JOIN PRODUCT P ON PL.PNO = P.ID WHERE PL.ID = 1;


DESC MENU;
DESC PRODUCT;
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PURCHASE';

DESC PURCHASE;
SELECT * FROM PURCHASE;

DESC PURCHASELIST;

SELECT * FROM PURCHASELIST;

ALTER TABLE PURCHASE ADD(CONSTRAINT PURCHASE_ID_PK PRIMARY KEY(ID));
ALTER TABLE PURCHASE ADD(CONSTRAINT PURCHASE_SNO_FK FOREIGN KEY(SNO) REFERENCES STORE(ID));



--ALTER TABLE PURCHASE DROP CONSTRAINT PURCHASE_ID_FK;

DESC MENU;
DESC PRODUCT;
DESC PURCHASE;
DESC PURCHASELIST;
DESC STORE;
SELECT ID,PRICE,PAYMENTDAY FROM PURCHASE WHERE TO_DATE(PAYMENTDAY,'YYYY-MM-DD') = TO_DATE(SYSDATE,'YYYY-MM-DD') ORDER BY PAYMENTDAY;


